apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: jpablovargas/jwt-auth:v1.1
        ports:
          - containerPort: 3000
          - containerPort: 3001
